Tasker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('task.urls',namespace='task'))
]

task/urls.py
from django.urls import path 
from .views import list_task, add_task,delete_task,update_task


app_name="task"
urlpatterns=[
    path("tasks",list_task, name="list_task"),
    path("add",add_task,name="add_task"),
    path("delete/<int:task_id>",delete_task,name="delete_task"),
    path("update/<int:task_id>",update_task,name="update_task")
]

task/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title=models.CharField(max_length=100)
    completed=models.BooleanField(default=False)


    def __str__(self):
        return self.title

task/views.py
from django.shortcuts import render,redirect
from .models import Task
from .form import TaskForm
# Create your views here.
def list_task(request):
    tasks=Task.objects.all()
    print(tasks)
    context= {'tasks':tasks}
    return render(request,"task_list.html",context)

def add_task(request):
    form= TaskForm()
    if request.method=="POST":
        data= TaskForm(request.POST)
        if data.is_valid(): 
            data.save()
            return redirect("/tasks")
    context={'form':form}
    return render(request,"add_task.html",context)

def delete_task(request,task_id):
    Task.objects.get(id=task_id).delete()
    return redirect("/tasks")

def update_task(request,task_id):
    task=Task.objects.get(id=task_id)
    task.completed= True
    task.save()
    return render(request,"task_list.html")

task/templates/add_task.html
{%extends 'base.html'%}

{% load django_bootstrap5 %}
{%block content%}
<h2 class="d-flex align-items-center justify-content-center" >
    Add New Task
    </h2>
    <hr>
   <div class="d-flex align-items-center justify-content-center">
<form method="post" action="{% url 'task:add_task'%}">
    {%csrf_token%} 
    
    {%bootstrap_form form %}
    <button class="btn btn-primary">
        Add New Task
    </button>
</form>
</div>
{%endblock%}

task/templates/task_list.html
{%extends 'base.html'%}
{%block content%}
<h2>
  My TaskList
  </h2>
  <a href="{%url 'task:add_task' %}" class="btn btn-primary" role="button" aria-disabled="true">Add New Task</a>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Completed</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>

    <tbody>
        {%for task in tasks%}
      <tr>
       
        <td>{{task.title}}</td>
        <td>{{task.completed}}</td>
        {%if not task.completed %}
        <td>
          <form action="{%url 'task:update_task' task.id %}" id="update-form">
            {%csrf_token%}
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
              Mark as Complete
            </label>
          </div>
          </form>
        </td>
        {%else %}
        <td>
        
        </td>
        {%endif%}
        <td>
          <a href="{%url 'task:delete_task' task.id %}" class="btn btn-danger" role="button" aria-disabled="true">Delete</a>
           </td>
        
      </tr>
      {%endfor%}
      
    </tbody>
  </table>
  <script>
    $(document).ready(function () {
        $('#flexCheckDefault').change(function () {
            if (this.checked) {
                
 
                // Checkbox is checked, send an AJAX request
                $.ajax({
                    url: $('#update-form').attr('action'),
                    type: 'GET',
                    success: function (response) {
                        window.location.href = "tasks"
                    },
                    error: function (xhr, status, error) {
                        console.error(error);
                    }
                });
            } else {
                // Checkbox is unchecked, clear the response container
                $('#ajax-response').empty();
            }
        });
    });
    </script>
{%endblock%}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Tasker</title>
  </head>
  <body>
    {%block content%}
    {%endblock%}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>